"""Adding_Employee_Table

Revision ID: 76e54af3a89d
Revises: 950ff5d5ed1e
Create Date: 2026-01-06 13:04:43.704508

"""
from typing import Sequence, Union

from alembic import op #type: ignore
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76e54af3a89d'
down_revision: Union[str, Sequence[str], None] = '950ff5d5ed1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
