"""initial_migration

Revision ID: 950ff5d5ed1e
Revises:
Create Date: 2026-01-06 11:44:17.709167

"""
from typing import Sequence, Union

from alembic import op #type: ignore
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '950ff5d5ed1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
