"""Change_optional_id

Revision ID: daa765486560
Revises: 1cb6c4d4cafc
Create Date: 2026-01-06 15:55:21.947802

"""
from typing import Sequence, Union

from alembic import op #type: ignore
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'daa765486560'
down_revision: Union[str, Sequence[str], None] = '1cb6c4d4cafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
