"""Adding_Employee_personal_info_Table.

Revision ID: 01a5e308d4a0
Revises: 76e54af3a89d
Create Date: 2026-01-06 13:38:17.759045

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01a5e308d4a0'
down_revision: str | Sequence[str] | None = '76e54af3a89d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employees_personal_info',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('employee_id', sa.Uuid(), nullable=False),
        sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('document_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column('education_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('personal_email', sa.String(length=255), nullable=False),
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('country_id', sa.Uuid(), nullable=True),
        sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ['employee_id'],
            ['employee.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('employee_id'),
        sa.UniqueConstraint('personal_email'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_personal_info')
    op.drop_table('employee')
    # ### end Alembic commands ###
