"""Adding_Employee_financial_info_Table.

Revision ID: 1cb6c4d4cafc
Revises: 01a5e308d4a0
Create Date: 2026-01-06 14:51:02.917884

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1cb6c4d4cafc'
down_revision: str | Sequence[str] | None = '01a5e308d4a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employee_financial_info',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('employee_id', sa.Uuid(), nullable=False),
        sa.Column('salary_amount', sa.DECIMAL(), nullable=False),
        sa.Column('salary_currency_id', sa.Uuid(), nullable=False),
        sa.Column('company_cost_amount', sa.DECIMAL(), nullable=False),
        sa.Column('effective_from', sa.Date(), nullable=False),
        sa.Column('effective_to', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['employee_id'],
            ['employee.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_financial_info')
    # ### end Alembic commands ###
