from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e8499e04162'
down_revision: Union[str, Sequence[str], None] = 'f6867092327c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employee_employee_code'), 'employee', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employee_financial_info_employee_id'), 'employee_financial_info', ['employee_id'], unique=False)
    op.alter_column('employees_personal_info', 'document_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(op.f('employees_personal_info_employee_id_key'), 'employees_personal_info', type_='unique')
    op.drop_constraint(op.f('employees_personal_info_personal_email_key'), 'employees_personal_info', type_='unique')
    op.create_index(op.f('ix_employees_personal_info_city'), 'employees_personal_info', ['city'], unique=False)
    op.create_index(op.f('ix_employees_personal_info_document_number'), 'employees_personal_info', ['document_number'], unique=True)
    op.create_index(op.f('ix_employees_personal_info_employee_id'), 'employees_personal_info', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_personal_info_personal_email'), 'employees_personal_info', ['personal_email'], unique=True)
    op.create_index(op.f('ix_employees_personal_info_phone'), 'employees_personal_info', ['phone'], unique=True)
    op.create_index(op.f('ix_employees_personal_info_tax_id'), 'employees_personal_info', ['tax_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_personal_info_tax_id'), table_name='employees_personal_info')
    op.drop_index(op.f('ix_employees_personal_info_phone'), table_name='employees_personal_info')
    op.drop_index(op.f('ix_employees_personal_info_personal_email'), table_name='employees_personal_info')
    op.drop_index(op.f('ix_employees_personal_info_employee_id'), table_name='employees_personal_info')
    op.drop_index(op.f('ix_employees_personal_info_document_number'), table_name='employees_personal_info')
    op.drop_index(op.f('ix_employees_personal_info_city'), table_name='employees_personal_info')
    op.create_unique_constraint(op.f('employees_personal_info_personal_email_key'), 'employees_personal_info', ['personal_email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('employees_personal_info_employee_id_key'), 'employees_personal_info', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees_personal_info', 'document_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_employee_financial_info_employee_id'), table_name='employee_financial_info')
    op.drop_index(op.f('ix_employee_employee_code'), table_name='employee')
    # ### end Alembic commands ###
